server:
  port: 9091
spring:
  application:
    name: Wipro-Security
  datasource:
    url: jdbc:mysql://localhost:3306/wipro
    username: root
    password: Reddy-333@
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true